[Rcon]
bEnabled=True
Password=killers
ListenPort=27015

;The following additional config variables are also available:
bUseBroadcastAddress=True
	
;If enabled, then the rcon socket will listen on all available network devices.
ListenAddressOverride=74.91.120.229
	
;If bUseBroadcastAddress is False, this is the network IP the rcon socket is bound to.
bAllowConsoleCommands=True

;When enabled, any unknown rcon commands will be interpreted as console commands.
MaxPasswordAttempts=3
	
;The maximum number of failed authentication attempts before the IP address is temporarily banned.
IncorrectPasswordBanTime=300
		
;To remove movement lag and stutter on server
[/Script/Engine.GameNetworkManager]
bMovementTimeDiscrepancyDetection=false
bMovementTimeDiscrepancyResolution=false

[/Script/Insurgency.INSGameMode]

;Name of Server
ServerHostname=Exstreams Insurgency Sandstorm Server

;Reveal distance of kills?
bKillerInfoRevealDistance=True

;Is the kill feed enabled for dedicated spectators and replays?
bKillerInfo=True
bKillFeed=True

;Spawn Protection
;Default for protection on move is true
bLoseSpawnProtectionOnMove=False

;Default for move grace is 0.3 second
LoseSpawnProtectionOnMoveGrace=0.9

;Is the kill feed enabled?
bKillFeedSpectator=True 	 	

;Limit for the number of team kills one player can perform before being kicked.	
TeamKillLimit=3 	
TeamKillGrace=0.2 	

;Grace timer between team killing incidents.
TeamKillReduceTime=90 	

;//////////////Messages\\\\\\\\\\\\\\\\\\ 

;Can alive players see messages from the dead?
bDeadSay=True  	

;Can alive players see messages from dead teammates using team-only chat?
bDeadSayTeam=True

;///////////////Chat\\\\\\\\\\\\\\\\\\ 

;Can alive players hear voice chat from dead players?	
bVoiceAllowDeadChat=True

;Can proximity voice chat be heard by enemies?	
bVoiceEnemyHearsLocal=True

;Can radio chat also broadcast on the local channel?	
bVoiceRadioBroadcastLocal=False

;Match Activity Implementation	
ActivityExperationTimeLimit=150

;Cancalation time in secconds 
ActivityCancellationTimeLimit=2100

;Show restricted areas for both teams	  	
bShowRestrictedAreaBothTeam=False 	

;Additional capture speed-up for each player on the point.
ObjectiveSpeedup=0.50

;Maximum players taken into account for capture speed-up.	
ObjectiveMaxSpeedupPlayers=2

;Disable vehicles for whole game? (Default is false)
bDisableVehicles=False

;Amount of time in seconds before weapon on group dissapear
DroppedWeaponLifespan=90


[/Script/Insurgency.INSMultiplayerMode]

;///////////////Timers\\\\\\\\\\\\\\\\\\ 

;The additional time to wait for additional players during the starting intermission.
GameStartingIntermissionTime=5 	
WinTime=5 	

;How long players are frozen before transitioning to the round intermission screen.
PostRoundTime=5 	

;How long is spent on the intermission screen.
PostGameTime=5 	

;Amount of “freeze time” at the start of a round. 	
PreRoundTime=1	

;Should teams be assigned on connect?
bAutoAssignTeams=True 		

;///////////////Frienly Fire\\\\\\\\\\\\\\\\\\ 

;Enables friendly fire.
FriendlyFireModifier=0 	
bAllowFriendlyFire=True 

;Damage modifier for friendly fire that is mirrored back at the attacker.
FriendlyFireReflect=0

;///////////////Map Cycle\\\\\\\\\\\\\\\\\\ 

;Enabled map voting at the end of each game.
;Map (Only 1 of them can be true)	
bMapVoting=True

;Enables the use of the map cycle. 
bUseMapCycle=False 	

;Allow both teams to talk to each other between rounds.
bVoiceIntermissionAllowAll=True 

;///////////////Idle Time\\\\\\\\\\\\\\\\\\ 	

;How long a player can be idle for before being kicked.
IdleLimit=150 	

;How long a player can idle for when there are low reinforcements.
IdleLimitLowReinforcements=90

;How frequently to check for idle players.	
IdleCheckFrequency=30	

;///////////////Game Time\\\\\\\\\\\\\\\\\\ 

;Maximum duration a game can last. Negative value disables.
GameTimeLimit=-1

;RoundTime 	Varies 	Duration of the round.
OverTime=60 	

;///////////////Team\\\\\\\\\\\\\\\\\\ 

;Minimum additional time spent between team switches.
TeamSwitchTime=10 	

;How often to switch teams. 0 = never, 1 = every round, 2 = every other round, etc.
SwitchTeamsEveryRound=0	

;Allow players to switch to the other team?
bAllowPlayerTeamSelect=False  	
bBots=False 

;Minimum players required on each team to start the game.
MinimumPlayers=1 

;Number of rounds required for game victory.
WinLimit=1 	

;Enables auto team balancing.	
bAutoBalanceTeams=True 	

;How long to wait after detecting unbalanced teams.
AutoBalanceDelay=10

;///////////////Supply\\\\\\\\\\\\\\\\\\ 

;Amount of starting supply points.	
InitialSupply=80

;Maximum supply that can be earned.	
MaximumSupply=90 	
bSupplyGainEnabled=False 	

;Should supply gain be awarded instantly?
bAwardSupplyInstantly=False

;Score threshold for earning supply.	
SupplyGainFrequency=150 	

;///////////////Spectators\\\\\\\\\\\\\\\\\\ 

;Can players use 3rd person spectator mode?	
bAllowThirdPersonSpectate=True 		


[/Script/Insurgency.INSCoopMode]

;///////////////Bots\\\\\\\\\\\\\\\\\\ 

;AI difficulty factor (0.0 - 1.0).
AIDifficulty=0.5 	

;Friendly bots for coop.	
FriendlyBotQuota=0	

;Minimum number of enemy bots.
MinimumEnemies=12

;Maximum number of enemy bots.	
MaximumEnemies=19 	

;///////////////Vehicle\\\\\\\\\\\\\\\\\\ 

;Use vehicle insertion sequences where possible.
bUseVehicleInsertion=True


[/Script/Insurgency.INSCheckpointGameMode]

;///////////////Timers\\\\\\\\\\\\\\\\\\ 

;Varies How long it takes to capture territorial objectives.
ObjectiveCaptureTime=20

;How long objective progress decays with no one on the point. Negative value disables.	
ObjectiveResetTime=-1

;Time bots will rush the cache after destruction.
PostCaptureRushTimer=20  

;Time to defend against counter attack with small player team.
DefendTimer=60 	

;Extend duration of counter-attack by this on the final point.
DefendTimerFinal=100

;Time to force bots to retreat after a counter-attack.	
RetreatTimer=5

;“Dead player ratio” that must be reached before respawning the bot team.	
RespawnDPR=0.1 	

;///////////////Respawn\\\\\\\\\\\\\\\\\\ 

;Bot respawn delay.
RespawnDelay=5 		

;“Dead player ratio” that must be reached before respawning the bot team during a counter-attack.
CounterAttackRespawnDPR=0.2

;Bot respawn delay during counter-attack.	
CounterAttackRespawnDelay=10

;Multiplier of bots to respawn with minimum player count. 	
ObjectiveTotalEnemyRespawnMultiplierMin=0.6

;Multiplier of bots to respawn with maximum player count.	
ObjectiveTotalEnemyRespawnMultiplierMax=1.0

;///////////////Multiplier\\\\\\\\\\\\\\\\\\ 

;Increase in bot quota for final objective if it’s a cache. 	
FinalCacheBotQuotaMultiplier=1.6

;///////////////Waves\\\\\\\\\\\\\\\\\\ 

;Enables the reinforcement waves system from local play	
bForceSoloWaves=True 
SoloWaves=10

;///////////////Round Time\\\\\\\\\\\\\\\\\\ 

;Each objective round time
RoundTime=1260	
SoloRoundTime=1260

;///////////////Ammo Box\\\\\\\\\\\\\\\\\\
 
;Amount of ammo box that spawn randomly 4 to 6 ammo box each objective
MinAmmoPerObjective=4
MaxAmmoPerObjective=6

;Ammobox spawn chance 1.0 = 100%
AmmoBoxSpawnChance=1.0

[/Script/Insurgency.VoteIssueKick]

;Can the vote target an enemy player?
bCanTargetEnemies=false 	

;Does this issue require a minimum number of players to show their voting intentions before commencing the vote?
bRequiresMinimumToStart=true 	

;How long a ban for any other reason will last in seconds.
DefaultVoteBanDuration=120

;How long voting an idle player will ban them for in seconds, -1 represents a kick only.	
IdleVoteBanDuration=-1 	

;Minimum ratio of team required to start a vote
MinimumPlayerRatio=0.25 	

;The number of players required to start a vote.
MinimumPlayersRequired=1

;For the vote to succeed, yes must have this number of votes over no.	
MinimumYesNoDifference=2

;Ratio of team required to vote yes for vote to pass.	
VotePassRatio=0.75

;How long until this vote can be called again.	
VoteTimeout=90 	

[/NoRestrictPlus/Mutators/NoRestrictPlus.NoRestrictPlus_C]

;Removes Restricted Area Warnings
RemoveRestricted=True 

;Removes Playable Area Warnings
RemovePlayable=True 

;True Removes Volumes That Prevent Player Access(Ex. On Roofs/Objects)
RemoveBlockingVolumes=False 

;True Allows Players To Pass Through One Another
RemovePlayerCollision=False 



















































